### ISSUE TITLE
Running PlateEditor from fresh install

### ISSUE THREAD

**Issue by yochannah** [vindelorme/PlateEditor#1]
Hey folks!

I'm trying to install PlateEditor locally, but get a couple of errors when I try to run it. I clone the repo, `npm install` it, and `npm run compil` (thansk for adding the npm setup instructions!). Then, when I open Editor.html in my browser, I get two errors in my js console: 

```js
Uncaught SyntaxError: redeclaration of let Pairing
    <anonymous> Area.js:4
Area.js:4
```

```js
Uncaught ReferenceError: Editor is not defined
    onload file:///snip-out-some-path/PlateEditor/Editor.html:18
    EventHandlerNonNull* file:///snip-out-some-path/PlateEditor/Editor.html:18
```

Am I doing something wrong here? On a fresh clone/install do you get the same by any chance? let me know if I missed something in the docs that I should have done.

Thanks!! :) :)

**Comment by vindelorme** [comment]
Dear user,
Thank you for your feedback! There was indeed an extra copy of the Pairing.js file in the editor package, which was causing the error you see. Apologies for that mistake... Please delete the file and try compiling again before refreshing the page, it should work fine. The source code has been updated (together with the release) to solve this issue.
Thank you for trying out PlateEditor and let us know if anything else goes wrong!
